# Generated by Django 3.1 on 2020-09-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
